/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "calc_test.check" instead.
 */

#include <check.h>

#line 1 "calc_test.check"
#include "calc.h"
#include "test_function.h"

START_TEST(expression_1) {
#line 5
  double result = 0.0;
  double expected = 10.0;
  test_calculator("5 + 5", "0", &result, &expected);
}
END_TEST

START_TEST(expression_2) {
#line 10
  double result = 0.0;
  double expected = -78546.476923;
  test_calculator("12-32*(2143-312*(4-5)-1.32/(83.2/3))", "0", &result,
                  &expected);
}
END_TEST

START_TEST(expression_3) {
#line 15
  double result = 0.0;
  double expected = 0.0;
  test_calculator("32mod(32-30)", "0", &result, &expected);
}
END_TEST

START_TEST(expression_4) {
#line 20
  double result = 0.0;
  double expected = -120526.054910;
  test_calculator("11-(123124.0001+(42-32.327)-32)*423/432", "0", &result,
                  &expected);
}
END_TEST

START_TEST(expression_5) {
#line 25
  double result = 0.0;
  double expected = 0.669268;
  test_calculator("(0.432*54.2/4^2-(-8*4))*0.02", "0", &result, &expected);
}
END_TEST

START_TEST(expression_6) {
#line 30
  double result = 0.0;
  double expected = 1.5;
  test_calculator("(2+3/2)mod2", "0", &result, &expected);
}
END_TEST

START_TEST(expression_7) {
#line 35
  double result = 0.0;
  double expected = 2769.160611;
  test_calculator("(1+(1*(4*(5^4+(3*2*1.1/(3*sin(2*cos(1235.3)*2)))))))", "0",
                  &result, &expected);
}
END_TEST

START_TEST(expression_8) {
#line 40
  double result = 0.0;
  double expected = 0.540302;
  test_calculator("cos(1)", "0", &result, &expected);
}
END_TEST

START_TEST(expression_9) {
#line 45
  double result = 0.0;
  double expected = 1.029639;
  test_calculator("tan(0.8)", "0", &result, &expected);
}
END_TEST

START_TEST(expression_10) {
#line 50
  double result = 0.0;
  double expected = 0.674741;
  test_calculator("atan(0.8)", "0", &result, &expected);
}
END_TEST

START_TEST(expression_13) {
#line 55
  double result = 0.0;
  double expected = 1.369438;
  test_calculator("acos(0.2)", "0", &result, &expected);
}
END_TEST

START_TEST(expression_14) {
#line 60
  double result = 0.0;
  double expected = 4;
  test_calculator("sqrt(16)", "0", &result, &expected);
}
END_TEST

START_TEST(expression_15) {
#line 65
  double result = 0.0;
  double expected = 53304.710856;
  test_calculator("ln(2)+ln(3)-4+(5*6)^3.2+sin(10)", "0", &result, &expected);
}
END_TEST

START_TEST(expression_16) {
#line 70
  double result = 0.0;
  double expected = 0.698970;
  test_calculator("log(5)", "0", &result, &expected);
}
END_TEST

START_TEST(expression_17) {
#line 75
  double result = 0.0;
  double expected = 512;
  test_calculator("2^3^2", "0", &result, &expected);
}
END_TEST

START_TEST(expression_18) {
#line 80
  double result = 0.0;
  double expected = 501.029639;
  test_calculator("2 + 2^3^2 - 14 + tan(0.8)", "0", &result, &expected);
}
END_TEST

START_TEST(expression_19) {
#line 85
  double result = 0.0;
  double expected = 11.585040;
  test_calculator("(1+2)*4*cos(x*7-2)+sin(2*x)", "3", &result, &expected);
}
END_TEST

START_TEST(expression_20) {
#line 90
  double result = 0.0;
  int expected_code = 1;
  test_input("(1+2)*4*cs(x*7-2)+sn(2*x)", "3", &result, &expected_code);
}
END_TEST

START_TEST(expression_21) {
#line 95
  double result = 0.0;
  int expected_code = 1;
  test_input("(2+3/2)m2", "0", &result, &expected_code);
}
END_TEST

START_TEST(expression_22) {
#line 100
  double result = 0.0;
  int expected_code = 1;
  test_input("lg(5)", "0", &result, &expected_code);
}
END_TEST

START_TEST(expression_23) {
#line 105
  double result = 0.0;
  int expected_code = 1;
  test_input("4mo", "0", &result, &expected_code);
}
END_TEST

START_TEST(expression_24) {
#line 110
  double result = 0.0;
  int expected_code = 1;
  test_input("acs(0.2)", "0", &result, &expected_code);
}
END_TEST

START_TEST(expression_25) {
#line 115
  double result = 0.0;
  int expected_code = 0;
  test_input("tan(0.8)", "0", &result, &expected_code);
}
END_TEST

START_TEST(expression_26) {
#line 120
  float principal = 54578364.0;
  float interest_rate = 12.0;
  int term = 6;
  const char payment_type[255] = "annuity";
  float payment = 0.0, overpayment = 0.0, total_payment = 0.0;
  float expected_payment = 1067018.125000;
  float expected_overpayment = 22246948.000000;
  float expected_total_payment = 76825312.000000;
  test_credit_calculator(principal, interest_rate, term, payment_type, &payment,
                         &overpayment, &total_payment, &expected_payment,
                         &expected_overpayment, &expected_total_payment);
}
END_TEST

START_TEST(expression_27) {
#line 131
  float principal = 3000000.0;
  float interest_rate = 14.0;
  int term = 4;
  const char payment_type[255] = "differential";
  float payment = 0.0, overpayment = 0.0, total_payment = 0.0;
  float expected_payment = 63229.167969;
  float expected_overpayment = 857500.000000;
  float expected_total_payment = 3857500.000000;
  test_credit_calculator(principal, interest_rate, term, payment_type, &payment,
                         &overpayment, &total_payment, &expected_payment,
                         &expected_overpayment, &expected_total_payment);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, expression_1);
  tcase_add_test(tc1_1, expression_2);
  tcase_add_test(tc1_1, expression_3);
  tcase_add_test(tc1_1, expression_4);
  tcase_add_test(tc1_1, expression_5);
  tcase_add_test(tc1_1, expression_6);
  tcase_add_test(tc1_1, expression_7);
  tcase_add_test(tc1_1, expression_8);
  tcase_add_test(tc1_1, expression_9);
  tcase_add_test(tc1_1, expression_10);
  tcase_add_test(tc1_1, expression_13);
  tcase_add_test(tc1_1, expression_14);
  tcase_add_test(tc1_1, expression_15);
  tcase_add_test(tc1_1, expression_16);
  tcase_add_test(tc1_1, expression_17);
  tcase_add_test(tc1_1, expression_18);
  tcase_add_test(tc1_1, expression_19);
  tcase_add_test(tc1_1, expression_20);
  tcase_add_test(tc1_1, expression_21);
  tcase_add_test(tc1_1, expression_22);
  tcase_add_test(tc1_1, expression_23);
  tcase_add_test(tc1_1, expression_24);
  tcase_add_test(tc1_1, expression_25);
  tcase_add_test(tc1_1, expression_26);
  tcase_add_test(tc1_1, expression_27);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
